// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Artists = sequelize.define('artists', {
    name: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'artists',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Artists.associate = (models) => {
    Artists.belongsToMany(models.links, {
      through: 'playlists',
      foreignKey: 'artist_id',
      otherKey: 'link_id',
      as: 'linksThroughPlaylists',
    });
  };

  return Artists;
};
