// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Experts = sequelize.define('experts', {
    username: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'experts',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Experts.associate = (models) => {
    Experts.belongsToMany(models.skills, {
      through: 'experts_skills',
      foreignKey: 'expert_id',
      otherKey: 'skill_id',
      as: 'expertSkills',
    });
  };

  return Experts;
};
