// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Playlists = sequelize.define('playlists', {
  }, {
    tableName: 'playlists',
    underscored: true,
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Playlists.associate = (models) => {
    Playlists.belongsTo(models.artists, {
      foreignKey: {
        name: 'artistIdKey',
        field: 'artist_id',
      },
      as: 'artist',
    });
    Playlists.belongsTo(models.links, {
      foreignKey: {
        name: 'linkIdKey',
        field: 'link_id',
      },
      as: 'link',
    });
  };

  return Playlists;
};
