// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Skills = sequelize.define('skills', {
    description: {
      type: DataTypes.STRING,
      validate: {
        // len: [3,10],
        // is: ["/com$/"],
        isUrl: true,
      },
    },
  }, {
    tableName: 'skills',
    timestamps: false,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Skills.associate = (models) => {
    Skills.belongsToMany(models.experts, {
      through: 'experts_skills',
      foreignKey: 'skill_id',
      otherKey: 'expert_id',
      as: 'skillExperts',
    });
  };

  return Skills;
};
